# Generated by Django 3.2.6 on 2021-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_author_authoravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authorAvatar',
            field=models.ImageField(default=None, height_field='100', null=True, upload_to='', width_field='100%'),
        ),
    ]
