# Generated by Django 3.2.6 on 2021-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_author_authoravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorAvatar',
            field=models.ImageField(height_field='100', null=True, upload_to='', width_field='100%'),
        ),
    ]
