# Generated by Django 3.2.6 on 2021-09-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_author_authoravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorAvatar',
        ),
    ]
