# Generated by Django 3.2.6 on 2021-09-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NWS', 'Новость'), ('ART', 'Статья'), ('RVW', 'Обзор')], default='ART', max_length=3),
        ),
    ]
