# Generated by Django 3.2.6 on 2021-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20211025_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
