# Generated by Django 3.2.6 on 2021-10-30 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_post_isupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
